# Request
# The position in x,y coordinates

float32 x
float32 y
float32 theta
bool predicted_exploration

---

# Response
# true means that the grid cell has been covered by the camera window

bool success  # True if the sequence was successful
