# request
robo7_msgs/cornerList the_lidar_corners
robo7_msgs/cornerList the_wall_corners
geometry_msgs/Twist current_position
---
robo7_msgs/Matrix4 transformation
float64 error
geometry_msgs/Twist new_position
bool success  # True if the sequence was successful
