# request
geometry_msgs/Twist robot_position
geometry_msgs/Point destination_position
---
robo7_msgs/trajectory path_planned
geometry_msgs/Twist destination_pose
bool success  # True if the sequence was successful
