# request
geometry_msgs/Twist object_pos    # position of the object to pickup, in the robot frame
bool drop                         # do we want to run it in drop mode?
---
bool success  # True if the pickup sequence was sucsessful
