# request
robo7_msgs/XY_coordinates point_cloud  # position of the object to pickup, in the map coordinates
---
robo7_msgs/cornerList all_corners
bool success  # True if the pickup sequence was sucsessful
