# Request
# Take as input both previous occupancy grid and the robot_pose timed
# joined with the corresponding lidar scan (aka the_robot_position)

robo7_msgs/mapping_grid current_occupancy_grid

---

# Response
# The response is an updated version of the occupancy grid

bool success
